# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0d24bb9e1d05b90b32422be4763312eef00cc8a9b8c0d8aa3ba127eb1874dddd76734695047821eb0da25a296ee78d3af48dd8c58fd3f6045963ada48df30a9

test:
  secret_key_base: 2b0b8514be28519df2c62a32368a7ff985b82c354a215e70ccb5696573614e18cb0cf62008f095c34e641661cb79366f7566859dd3329b341c02ece49f215898

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
